/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_engine_jni_V8JNI */

#ifndef _Included_com_engine_jni_V8JNI
#define _Included_com_engine_jni_V8JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_engine_jni_V8JNI
 * Method:    parseRules
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_engine_jni_V8JNI_parseRules
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_engine_jni_V8JNI
 * Method:    execInterpreter
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_engine_jni_V8JNI_execInterpreter
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
